### ISSUE TITLE
reading enum from ConstantReader

### ISSUE THREAD

**Issue by Huholoman** [simphotonics/generic_reader#3]
Hello,
Im trying to get enum from ConstantReader. Ive found your library and tried to use it.

I have annotation with  `StrategyEnum? strategy` property. So In my code where Im trying to read the `strategy` property I tried this
```dart
final strategy = constantReader.get<StrategyEnum?>();
```

Unfortunately it threw error: `ErrorOf<ConstantReader>: "Input does not represent an object of type <StrategyEnum?>"`

I think I may be using your generic_reader incorrectly as I would expect `get` method to accept property name :thinking: 

Thanks in advance!

**Comment by simphotonics** [comment]
The extension `GenericReader` can handle Dart enums and in the following I am assuming that `StrategyEnum` is a Dart enum. However, `StrategyEnum?` is a completely different type that is not known to `GenericReader`, unless you define a custom `Decoder`. 

You could either:
1)  define a `Decoder` that can handle `StrategyEnum?`:
```Dart
 // Adding a decoder for constants of type StrategyEnum?.
  GenericReader.addDecoder<StrategyEnum?>((constantReader) {
    if (constantReader.isNull) { 
       return null;
    }else{
       return constantReader.get<StrategyEnum>();
    }
 });   
```


2) If it is your code, I would recommend refactoring the variable `strategy` by making it non nullable. For example, you could use `Strategy.none` to represent the absence of a strategy instead of `null`.
Then you can use:
```Dart
final strategy = constantReader.get<StrategyEnum>();
```
